// NOTIF ACTION
export const NOTIF_SUCCESS = "NOTIF_SUCCESS";
export const NOTIF_ERROR = "NOTIF_ERROR";
export const CLOSE_NOTIF = "CLOSE_NOTIF";

// LOADING ACTION
export const PROCESSING = "PROCESSING";
export const FINISHED = "FINISHED";

// GLOBAL ACTION
export const GLOBAL_STATE = "GLOBAL_STATE";
export const GET_STATE = "GET_STATE";
export const ADD_STATE = "ADD_STATE";
export const UPDATE_STATE = "UPDATE_STATE";
export const DELETE_STATE = "DELETE_STATE";
